version: '3'

services:
  app:
    container_name: sunchales-app
    build: .
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://localhost:27017/sunchales-dev
      - STAFF=bar@democracyos.io,lucianavegaf@gmail.com,florenciacaffarone@gmail.com
      - NOTIFICATIONS_MAILER_EMAIL=municipalidad@sunchales.gov.ar
      - NOTIFICATIONS_MAILER_NAME='Sunchales Participa'
      - JWT_SECRET=*****PleaseChangeThis
      - NOTIFICATIONS_NODEMAILER={"host":"smtp.mailtrap.io","port":2525,"auth":{"user":"15ddc6a0c81af9","pass":"062bf047627e63"}}
      - CUSTOM_SIGNIN=true/false
      - OIDC_ISSUER=**************
      - OIDC_AUTH=**************
      - OIDC_TOKEN=**************
      - ORGANIZATION_NAME=Sunchales Participa
      - SOCIALSHARE_SITE_NAME=Sunchales Participa
      - SOCIALSHARE_SITE_DESCRIPTION='Plataforma de participación ciudadana de Sunchales Participa.'
      # - OIDC_USER=**************
      # - OIDC_CLIENT_ID=**************
      # - OIDC_CLIENT_SECRET=**************
      # - OIDC_CALLBACK=**************
    ports:
      # - 3000:3000
      - 192.168.88.76:3000:3000 
    network_mode: "host"
    volumes:
      - ./ext/lib:/usr/src/ext/lib
      - ./public:/usr/src/public
      # Add every forced override to democracyos
      - ./dos-override/models/comment.js:/usr/src/lib/models/comment.js
      - ./dos-override/api-v2/db-api/comments/index.js:/usr/src/lib/api-v2/db-api/comments/index.js
      - ./dos-override/api-v2/db-api/comments/scopes.js:/usr/src/lib/api-v2/db-api/comments/scopes.js
    tty: true

 # mongo:
  #  container_name: sunchales-mongo
   # image: mongo:3.2
    #ports:
     # - 27017:27017
    #volumes:
     # - ./tmp/db:/data/db